fail when updated example does not fail
Example output of the error case:

```
 unexpected on feature/site* $ make update-examples
node site/update-examples.js

/home/gustav/Projects/unexpected/site/update-examples.js:111
        throw err;
              ^
Error: No errors were thrown when evaluating example in:
       /home/gustav/Projects/unexpected/documentation/any/to-equal.md

expect({ a: { b: 'c'} }, 'to equal', { a: { b: 'c'} });

    at /home/gustav/Projects/unexpected/site/update-examples.js:85:33
    at iterate (/home/gustav/Projects/unexpected/node_modules/async/lib/async.js:149:13)
    at /home/gustav/Projects/unexpected/node_modules/async/lib/async.js:160:25
    at /home/gustav/Projects/unexpected/site/update-examples.js:105:24
    at iterate (/home/gustav/Projects/unexpected/node_modules/async/lib/async.js:149:13)
    at /home/gustav/Projects/unexpected/node_modules/async/lib/async.js:160:25
    at /home/gustav/Projects/unexpected/site/update-examples.js:105:24
    at iterate (/home/gustav/Projects/unexpected/node_modules/async/lib/async.js:149:13)
    at Object.async.eachSeries (/home/gustav/Projects/unexpected/node_modules/async/lib/async.js:165:9)
    at /home/gustav/Projects/unexpected/site/update-examples.js:72:15
Makefile:59: recipe for target 'update-examples' failed
make: *** [update-examples] Error 8
```