Build with node 8.16.2 instead of 8.7.0
Avoids this error due to an eslint update:

/home/travis/build/unexpectedjs/unexpected/node_modules/eslint/lib/rules/no-octal-escape.js:41
                    /^(?:[^\\]|\\.)*?\\([0-3][0-7]{1,2}|[4-7][0-7]|0(?=[89])|[1-7])/su
                    ^
SyntaxError: Invalid regular expression flags

(cherry picked from commit cd4c62faa74e3de230b6a295b2d9f129a22869c0)